Read Presets from a directory.
TestRunnerSRL/OoT-Randomizer pull request #1172
Opened 2020-11-18 22:06 UTC by Cuphat

This changes the GUI to pull presets from any .json file in the 'data/Presets' directory instead of just the singular 'data/presets_default.json'. This brings back a little known and little used feature of the old tkinter GUI to be able to easily share presets.

2020-11-20 03:23 UTC, dragonbane0 requested changes
Not ready to get rid of the preset_default yet, so we need some changes

2020-11-20 03:23 UTC, dragonbane0 commented on GUI/electron/src/main.ts
> +  let builtInPresetsPath = path.normalize(pythonRootPath + "data/Presets");
As discussed, this should still account for the preset_default.json instead of removing it

2020-11-20 05:00 UTC, Cuphat commented
Alright, it now also reads from presets_default.json instead of splitting that up into separate files in the `data/Presets` directory. I want to reiterate how much I hate JavaScript.

2020-11-21 01:58 UTC, dragonbane0 approved these changes

2020-11-27 17:41 UTC, merged