All Goals Reachable setting
TestRunnerSRL/OoT-Randomizer pull request #1198
Opened 2020-12-03 05:56 UTC by fenhl

This implements #1196 as a variant of Beatable Only (which is now called Required Only in the GUI) by checking if all goal items are still reachable upon placing each item. Some things to note:

* I've only done minimal testing, i.e. checked that a seed generates successfully.
* This adds the explanation by analogy with speedrunning categories to the tooltip, but does not move “no logic” into this setting as proposed by @puddydoo. (I think it makes more sense to discuss that separately.)
* There's a weird visual bug where the tooltip for this setting appears behind the dropdown, making the text unreadable. @dragonbane0 any ideas on how to fix this?

2020-12-03 06:15 UTC, LostThePirate commented
Not a fan of the tooltip; I don't think the "speedrun category" analogy is appropriate here, especially since the *vast* majority of players do not come from a speedrunning background. I think these comparisons only muddy the explanation of the new categories, not clarify them.

2020-12-03 06:33 UTC, fenhl commented
I wasn't aware of that. Removed that part.

2020-12-03 06:42 UTC, LostThePirate commented
One of the most *vocal* segments of the community is the racers, who often also have a speedrunning background. But there are thousands more seeds rolled a day on the website than there are races, and we kinda have to assume that many of those are more casual players who don't come around the Discord for racing and whatnot.

2020-12-03 07:08 UTC, fenhl commented
Question regarding Bingosync: Are there detailed rules anywhere? For example, I'm wondering what the definition of an “Adult Dungeon” is.

2020-12-03 07:15 UTC, LostThePirate commented
Discord user DobbyDigital#1186 added the Bingo Hints system, so they could probably clarify further, but I believe they are generally based on/modified from vanilla OoT Bingo goals. Iirc, "dungeon" is specifically blue-warp dungeons, so Adult Dungeons would be the Temples.

2020-12-03 11:19 UTC, dragonbane0 commented
>  @dragonbane0 any ideas on how to fix this?

This usually happens when a tooltip line is too long. Try breaking earlier. Generally keep lines relatively short since there usually is more height then there is width.

2020-12-03 12:35 UTC, puddydoo commented
I think "100%" still helps explain ALR without a speedrunning context.

2020-12-04 04:18 UTC, fenhl commented
Since there is significant opposition to the idea of integrating AGR with Bingo, I will not be including it in this PR.

2020-12-04 07:50 UTC, fenhl commented
> This usually happens when a tooltip line is too long. Try breaking earlier. Generally keep lines relatively short since there usually is more height then there is width.

That didn't fix it, not even after putting each word on its own line.

2021-02-21 20:12 UTC, Zannick requested changes

2021-02-21 20:12 UTC, Zannick commented on Location.py
> +    def can_fill(self, state, item, check_access=True, extra_location_checks=[]):
```suggestion
    def can_fill(self, state, item, check_access=True, extra_location_checks=()):
```
Avoid mutable defaults.

2021-02-21 20:12 UTC, Zannick commented on Location.py
> +        if len(extra_location_checks) == 0:
```suggestion
        if not extra_location_checks:
```

2021-02-21 20:12 UTC, Zannick commented on Location.py
> +        return all(search_with_this.visited(extra_location) for extra_location in extra_location_checks)
```suggestion
        search_with_this.collect_locations(chain(search_with_this.progression_locations(), extra_location_checks))
        return all(map(search_with_this.visited, extra_location_checks))
```
You'll need `from itertools import chain` at the top if you take this suggestion.

2021-02-21 22:58 UTC, fenhl commented
Suggestions applied.

2021-02-21 23:11 UTC, Zannick approved these changes

2021-02-27 16:03 UTC, merged