Closed Forest with ER and adult start
TestRunnerSRL/OoT-Randomizer pull request #1305
Opened 2021-05-12 03:21 UTC by puddydoo

Closed Forest is made to work with all forms of ER and with adult start.
Adult start requires either ER or open door of time.
Closed Forest is also changed to only gate the forest exit, and the requirement of defeating Gohma to leave the forest is moved to a separate logical setting.

2022-03-03 16:43 UTC, fenhl requested changes

2022-03-03 16:43 UTC, fenhl commented on World.py
> +            not (self.open_door_of_time or ('Ocarina' and 'Song of Time') in self.distribution.starting_items or \
`'Ocarina' and 'Song of Time'` just evaluates to `'Song of Time'`.

2022-03-03 16:43 UTC, fenhl commented on World.py
> +                # adult is not compatible with glitchless closed forest without shuffled entrances or open door of time
A comment explaining why this is the case would be nice. It took us a while to figure out why the Door of Time setting affects this #dev-glitchless-logic.

2022-03-03 16:43 UTC, fenhl commented on data/World/Overworld.json
> +                (open_forest != 'closed' or starting_age == 'child' or here(is_child) or
I think there should be a comment here explaining why these logical requirements exist.

2022-03-03 16:46 UTC, fenhl commented
Judging from the amount of discussion that happened after I mentioned this in Discord, this seems to be a rather controversial setting. As such, it might make more sense to split this up into multiple smaller PRs that can be discussed and merged/rejected individually. I'm considering starting with splitting off “Closed Forest Requires Gohma” into a separate setting.

2022-04-11 06:34 UTC, cjohnson57 commented
This has been split off into more up to date PRs by fenhl.

2022-04-11 06:34 UTC, closed without merging

2022-04-11 06:45 UTC, fenhl commented
My current PRs (#1531 and #1536, for reference) don't cover all of the changes made here, but I plan to do more work in this area later (perhaps once decisions on the 2 open ones have been made).