Add unit test for duplicate message ID checks
TestRunnerSRL/OoT-Randomizer pull request #1977
Opened 2023-05-16 17:29 UTC by rrealmuto

Because we keep running into this problem.

2023-05-16 19:46 UTC, fenhl commented
I'd suggest moving this into CI since it's one a fast check that doesn't require rolling a seed. It also doesn't need to be called from Patches.

2023-05-17 13:19 UTC, rrealmuto commented
I included the call in Patches for development purposes (that's where I originally put the check so I would see every time it broke). 

As for moving it into CI, I'm not sure I follow. Isn't that exactly what I did by adding a unit test?

2023-05-17 13:36 UTC, fenhl commented
> I included the call in Patches for development purposes (that's where I originally put the check so I would see every time it broke). Maybe we keep it there in case someone decides to implement custom message plando ;)

I don't follow. How would that help in that case? And even then, I think it's unnecessary right now (at least with my other suggested change), since it's re-checking something that's already handled by CI. All it does is add a small amount of time to seed generation.

> As for moving it into CI, I'm not sure I follow. Isn't that exactly what I did by adding a unit test? Or do you mean add it to the --no-unit-tests part of CI?

Yes, that's what I mean. CI with `--no_unit_tests` is a lot faster than running the entire thing so it's something that people can add as pre-commit hooks.

2023-05-20 16:58 UTC, rrealmuto commented
So I thought about your comment on how it was still missing messages that are modified from within Patches.py. I updated the runtime check to account for that so I think now it's definitely not redundant. If anything, now the CI one is 😂

2023-06-06 01:53 UTC, mracsys commented
A few more places that this trips in Patches.py that should have `allow_duplicates=True`:
1. Maps/Compasses give info enabled, there are three calls in the if block starting on [line 2271](https://github.com/OoTRandomizer/OoT-Randomizer/blob/399123e6c7d3877083886d80ebf7e6e81b542a8a/Patches.py#L2271)
2. Blue Fire Arrows enabled, one call on [line 2396](https://github.com/OoTRandomizer/OoT-Randomizer/blob/399123e6c7d3877083886d80ebf7e6e81b542a8a/Patches.py#L2396)
3. (For documentation, not relevant to the main branch) On Roman's branch, the fast token changes on [line 2360](https://github.com/Roman971/OoT-Randomizer/blob/284d2df92d4d980c55fa50dca43b2b52f7956327/Patches.py#L2360)

2023-06-17 21:49 UTC, cjohnson57 commented
This is definitely a great change considering how often this issue trips us up, lol

I agree that it's better to have the non-CI check so that you can catch it before opening a PR. 


> A few more places that this trips in Patches.py that should have `allow_duplicates=True`:
> 
> 1. Maps/Compasses give info enabled, there are three calls in the if block starting on [line 2271](https://github.com/OoTRandomizer/OoT-Randomizer/blob/399123e6c7d3877083886d80ebf7e6e81b542a8a/Patches.py#L2271)
> 2. Blue Fire Arrows enabled, one call on [line 2396](https://github.com/OoTRandomizer/OoT-Randomizer/blob/399123e6c7d3877083886d80ebf7e6e81b542a8a/Patches.py#L2396)
> 3. (For documentation, not relevant to the main branch) On Roman's branch, the fast token changes on [line 2360](https://github.com/Roman971/OoT-Randomizer/blob/284d2df92d4d980c55fa50dca43b2b52f7956327/Patches.py#L2360)

So the feature as-is gives false positives with these settings?

2023-06-17 21:51 UTC, mracsys commented
It does for the first two settings in this branch if they are turned on. I have a PR to fix them here: https://github.com/rrealmuto/OoT-Randomizer/pull/78

2023-11-14 00:38 UTC, cjohnson57 approved these changes

2024-02-15 14:25 UTC, fenhl requested changes
A couple code style changes, looks good other than that.

2024-02-15 14:25 UTC, fenhl commented on CI.py
> +                        error("Duplicate MessageID found: " + hex(message_id1) + ", " + message1 + ", " + message2, False)
```suggestion
                        error(f'Duplicate MessageID found: {hex(message_id1)}, {message1}, {message2}', False)
```

2024-02-15 14:25 UTC, fenhl commented on Messages.py
> +        raise Exception("Attempting to add duplicate message " + hex(id))
```suggestion
        raise Exception(f'Attempting to add duplicate message{hex(id)}')
```

2024-02-15 14:25 UTC, fenhl commented on Patches.py
> +        update_message_by_id(messages, 0x908B, "That's OK!\x01More fun for me.\x0B\x02", 0x00, True)
```suggestion
        update_message_by_id(messages, 0x908B, "That's OK!\x01More fun for me.\x0B\x02", 0x00, allow_duplicates=True)
```

2024-03-19 23:13 UTC, merged