Custom ice traps
TestRunnerSRL/OoT-Randomizer pull request #1982
Opened 2023-05-20 19:25 UTC by rrealmuto

Adds setting to select a custom amount of ice traps. When pots/crates/etc. are enabled, there is a pretty big jump between Ice Trap "Mayhem" and "Onslaught" because all of the junk items from pots don't get included under Mayhem. This setting allows more fine-grained control over how many ice traps are in the seed.

Two additional items are available under the "Ice Traps" drop down:
- Custom (count):  Specify an exact amount of "Junk" items to be converted to Ice Traps
- Custom (%): Specify a percentage of the "Junk" items to be converted to Ice Traps.

In both of these cases, "Junk" items includes base pool junk.

2023-06-17 21:55 UTC, cjohnson57 commented
Requesting to resolve merge conflicts/update to the new typing reqs, this PR is fairly small so hopefully shouldn't be too bad

2023-06-20 23:10 UTC, rrealmuto commented
Still need to make sure this actually works but I rebased it.

2023-06-23 15:35 UTC, rrealmuto commented
It seems to be working now. Found a problem where it wasn't properly working because of pending junk but I think that's fixed now.

2023-06-25 00:06 UTC, cjohnson57 commented
A couple things:

The count option goes up to 4 digits, but it looks like the box only displays up to 3. You'll probably have to dig into the forbidden CSS files for this
![image](https://github.com/OoTRandomizer/OoT-Randomizer/assets/30701749/2effa16d-3057-4ec5-a641-6578ad355c7c)

Just to confirm, I noticed that if I set the count way too high, instead of erroring it simply gives the same amount of ice traps as if I set it to 100%, this is intended behavior? (Ftr I think it's good)

2024-09-18 00:03 UTC, fenhl requested changes
Got some code style nits, this seems good other than that.

2024-09-18 00:03 UTC, fenhl commented on ItemPool.py
> +
```suggestion
```

2024-09-18 00:03 UTC, fenhl commented on ItemPool.py
> +    for i, val in enumerate(pool):
`i` is unused here.

```suggestion
    for val in pool:
```

2024-09-18 00:03 UTC, fenhl commented on ItemPool.py
> +    for i,val in enumerate(items):
```suggestion
    for i, val in enumerate(items):
```

2024-09-18 00:03 UTC, fenhl commented on ItemPool.py
> +    if world.settings.junk_ice_traps in ['off', 'custom_count', 'custom_percent']:
```suggestion
    if world.settings.junk_ice_traps in ('off', 'custom_count', 'custom_percent'):
```

2024-09-18 00:03 UTC, fenhl commented on ItemPool.py
> +    if world.settings.junk_ice_traps in ['custom_count', 'custom_percent']:
```suggestion
    if world.settings.junk_ice_traps in ('custom_count', 'custom_percent'):
```

2024-09-18 00:03 UTC, fenhl commented on SettingsList.py
> +            'Custom (count)' : Allows specifying a specific number of
```suggestion
            'Custom (count)': Allows specifying a specific number of
```

2024-09-18 00:03 UTC, fenhl commented on SettingsList.py
> +            'Custom (%)' : Allows specifiying a percentage of
```suggestion
            'Custom (%)': Allows specifiying a percentage of
```

2024-09-20 19:10 UTC, fenhl approved these changes

2024-09-30 11:33 UTC, fenhl commented
I must have done something wrong so GitHub didn't auto-close this PR, but this was merged in a75ab38692a264948d49466fce2411d03048a563.

2024-09-30 11:33 UTC, closed without merging