Replace Magic Meter Items
TestRunnerSRL/OoT-Randomizer pull request #2081
Opened 2023-09-02 17:19 UTC by Maplesstar

Replaces both the base and double magic items with a bar. Color matches cosmetics.
Doing this to free up the regular magic models for randomizing magic refills as junk items in the pool in the future.
Chose to do the same model for both base and double magic because it's a bar, getting a second and sticking it to the first makes sense to me and making a longer one isn't really feasible without allowing it to poke out of it's space, like the box in Graveyard.

![image](https://github.com/OoTRandomizer/OoT-Randomizer/assets/69886167/1b0e2081-aff2-41d2-8393-57b8200480b8)
![image](https://github.com/OoTRandomizer/OoT-Randomizer/assets/69886167/ab1caa7f-e00d-4ff9-94c4-69d0c7ed18a1)
![image](https://github.com/OoTRandomizer/OoT-Randomizer/assets/69886167/14bf3874-4e82-4a48-b5d4-8e245e8fc463)

2023-09-02 17:58 UTC, Natheirean commented
This is just a personal opinion from a runner's perspective, but I don't like the idea of this being the new magic model for magic/double magic. At the very least I would prefer an option to keep the older models in use. The model just doesn't seem all that appealing to me compared to the original models

2023-09-02 18:40 UTC, Maplesstar commented
> This is just a personal opinion from a runner's perspective, but I don't like the idea of this being the new magic model for magic/double magic. At the very least I would prefer an option to keep the older models in use. The model just doesn't seem all that appealing to me compared to the original models

My goal is to allow those models to be used for their original purpose of magic refills, which we could then add as additional junk items. I am happy to take criticism on the models to replace them, but I would choose to remove this PR over making it an option since it would prevent making magic refills an item and defeat the entire point.

2023-09-02 20:16 UTC, Natheirean commented
> > This is just a personal opinion from a runner's perspective, but I don't like the idea of this being the new magic model for magic/double magic. At the very least I would prefer an option to keep the older models in use. The model just doesn't seem all that appealing to me compared to the original models
> 
> My goal is to allow those models to be used for their original purpose of magic refills, which we could then add as additional junk items. I am happy to take criticism on the models to replace them, but I would choose to remove this PR over making it an option since it would prevent making magic refills an item and defeat the entire point.

Ya, I understand the purpose of it. And maybe its just me being resistant to change, but imagining seeing that as the new magic meter just feels weird to me. And I imagine for people not following the changes for this, that the new model will throw a lot of people off when it gets merged into main dev. Like it would probably warrant an announcement.

2023-09-02 20:45 UTC, Maplesstar commented
We have the dev changelog which shows changes. I personally believe dev changes don't warrant special announcements. Especially because this is a purely visual change. We've never had announcements for major functional changes, so I see no reason to do this one special. And once a new stable releases, there's the big changelog available for that.

2023-09-05 08:32 UTC, SlyryD commented
Could we instead put a clear tetrahedron around a magic jar (similar to freestanding dins, fw, nl -- <https://static.wikia.nocookie.net/zelda_gamepedia_en/images/a/a8/OoT_Din%27s_Fire_Model.png/revision/latest?cb=20130312011354>) to indicate the magic meter?

UPDATE: Looks like there's a dlist for that: <https://github.com/zeldaret/oot/blob/8913c4fa0d2cec19db6e8b4d8598125977243c5d/assets/xml/objects/object_gi_goddess.xml#L4>. I wonder if that can be loaded easily.

2023-09-05 18:50 UTC, Maplesstar commented
> Could we instead put a clear tetrahedron around a magic jar (similar to freestanding dins, fw, nl -- https://static.wikia.nocookie.net/zelda_gamepedia_en/images/a/a8/OoT_Din%27s_Fire_Model.png/revision/latest?cb=20130312011354) to indicate the magic meter?
> 
> UPDATE: Looks like there's a dlist for that: https://github.com/zeldaret/oot/blob/8913c4fa0d2cec19db6e8b4d8598125977243c5d/assets/xml/objects/object_gi_goddess.xml#L4. I wonder if that can be loaded easily.

I do think this idea is worth exploring to have a comparison. Perhaps shrink the size of the magic jar slightly to give space for the semi transparent shape. Then if majority opinion is that the bar is not the best option, I will remove this PR. Unfortunately I don't know how to call portions of existing dlists in order to do try it myself.

2023-09-05 19:55 UTC, SlyryD commented
> > Could we instead put a clear tetrahedron around a magic jar (similar to freestanding dins, fw, nl -- https://static.wikia.nocookie.net/zelda_gamepedia_en/images/a/a8/OoT_Din%27s_Fire_Model.png/revision/latest?cb=20130312011354) to indicate the magic meter?
> > UPDATE: Looks like there's a dlist for that: https://github.com/zeldaret/oot/blob/8913c4fa0d2cec19db6e8b4d8598125977243c5d/assets/xml/objects/object_gi_goddess.xml#L4. I wonder if that can be loaded easily.
> 
> I do think this idea is worth exploring to have a comparison. Perhaps shrink the size of the magic jar slightly to give space for the semi transparent shape. Then if majority opinion is that the bar is not the best option, I will remove this PR. Unfortunately I don't know how to call portions of existing dlists in order to do try it myself.

I'll give it a try -- I'm working on adding magicjars back in (<https://github.com/SlyryD/OoT-Randomizer/commit/ba9e2a21268ae913543c136b03a1d84d79399f94>). I think it's not trivial because we'll need to load the object_gi_goddess file to access the dlist. But that might just be a false understanding.

2023-11-14 00:11 UTC, cjohnson57 commented
I'm still worried that sly's model looks a bit too similar to the spells, Maple's can't really be mistaken for anything else lol

2024-06-21 02:04 UTC, fenhl requested changes

2024-06-21 02:04 UTC, fenhl commented on ASM/c/item_draw_table.c
> +    [0x94] = { draw_gi_magic_meter,         { 0x06000A80, 0x06000F80, 0x060014C0, 0x00CE00FF, 0xFFFFFFFF, 0x000000FF } }, // Magic Meter , 0x000000FF -- 0x06000F70, 0x00CE00FF, --, 0x06009C0, 0x06001
Left in commented-out code.

```suggestion
    [0x94] = { draw_gi_magic_meter,         { 0x06000A80, 0x06000F80, 0x060014C0, 0x00CE00FF, 0xFFFFFFFF, 0x000000FF } }, // Magic Meter , 0x000000FF -- 0x06000F70, 0x00CE00FF, --, 0x06009C0, 0x06001030, 0x00CE00FF, 0xFFFFFFFF
```

2024-09-16 00:50 UTC, fenhl approved these changes

2024-09-30 11:53 UTC, merged