In-game input viewer
TestRunnerSRL/OoT-Randomizer pull request #2138
Opened 2023-11-12 19:05 UTC by GSKirox

This new cosmetic setting enables an in-game input viewer for the stick X/Y positions and all button presses except Start.
Dolphin screenshot : 
![inputviewer](https://github.com/OoTRandomizer/OoT-Randomizer/assets/65768236/c79e7fff-cf27-4814-a508-61d46ca58433)

The icons used are the ones in the tutorial textboxes, which is why sadly Start is missing since they never needed one.

The position used is almost certainly out of the CRT safe range, but this is an optional and not important rando information, and it's hard to find room on the screen without it being too distracting 😅

2023-11-12 19:18 UTC, r0bd0g commented
The OoT Speedrun rules state:
"Adapters and input displays are not allowed to give you more information than looking at an unmodified controller (so no exact values, ess range indicators, etc)."
So I don't think this setting should be allowed in races.

2023-11-12 19:22 UTC, GSKirox commented
I'll bring it to the dev-race-mods channel !

2023-11-13 23:11 UTC, cjohnson57 commented
This is really cool! Hopefully we can find a solution where, if necessary, the viewer is disabled for race seeds and that's acceptable to the race mods.

2024-02-15 10:39 UTC, fenhl commented on SettingsList.py
> +        gui_text       = 'Input viewer',
```suggestion
        gui_text       = 'Input Viewer',
```

2024-02-15 10:41 UTC, fenhl commented
@GSKirox Could you rebase this please? I can give this a proper review then.

2024-02-23 13:45 UTC, GSKirox commented
Rebased and pushed, sorry for the delay, i don't check github too often these days.

2024-02-29 02:01 UTC, fenhl requested changes
I've opened https://github.com/GSKirox/OoT-Randomizer/pull/5 with some code style fixes. This looks good otherwise.

2024-03-07 16:35 UTC, fenhl approved these changes

2024-03-07 16:37 UTC, GSKirox commented
Thanks #dev-public-talk for making me check github sometimes...
Again sorry for the delay.

2024-03-19 23:42 UTC, merged