Add an helpful textbox to warn players in Adult shooting gallery
TestRunnerSRL/OoT-Randomizer pull request #2142
Opened 2023-11-16 08:09 UTC by GSKirox

This is basically a copy of what is done is OoT3D Rando, so shoutouts to them !
If the player wins Adult shooting gallery without having a bow, they'll get 50 rupees but not the actual item. Vanilla behaviour, but definitely something that can trip up new players.

This adds an helpful textbox in that case that says ""Come back when you have your own bow and you'll get the real prize!".

This textbox will fade out automatically after 120 frames, or will disappear faster if you play the game again/read the sign/pull out the ocarina/open the door, so there's a chance a new player will still miss it before reading the message, but at least we tried !
Also it will only show once by save/quit, to try to not annoy players that actually know about this and wants to farm the 50 rupees.

2023-12-02 07:38 UTC, GSKirox commented
Here is what this looks like in game


https://github.com/OoTRandomizer/OoT-Randomizer/assets/65768236/8adac179-4cb3-44b1-b662-5fecf59a03fa

2024-02-15 10:27 UTC, fenhl requested changes
Small code style nit, looks good other than that

2024-02-15 10:27 UTC, fenhl commented on ASM/c/message.c
> +    if (!(z64_file.items[ITEM_BOW] == -1)) {
```suggestion
    if (z64_file.items[ITEM_BOW] != -1) {
```

2024-02-23 13:48 UTC, GSKirox commented
Rebased with requested change done.

2024-02-23 13:51 UTC, fenhl approved these changes

2024-03-19 23:59 UTC, merged