Document wonder_talk2 and remove the ones in Thieves' hideout
TestRunnerSRL/OoT-Randomizer pull request #2232
Opened 2024-05-30 10:54 UTC by GSKirox

Wonder_talk2 is an actor that displays a textbox when near a certain spot, either automatically or by pressing A (button turns to Check). They're mostly present at the start of Shadow Temple and in every room of Gerudo Training Ground, and have been removed in randomizer years ago for convenience.

This PR adds information on how they are removed, move this process out of Patches.py in Cutscenes.py (it's not really cutscenes but it fits here imo), and use the same method to remove the ones in Thieves' Hideout when you get near a Carpenter's cell : 
_Hey, you! Young man, over there!
Look over here, inside the cell!_

The wonder_talk2 at the Crater Fairy entrance was patched differently from the other ones, but as far as i can see, there's no real advantage to this, so i changed it to use the same method as the other ones.

2024-05-30 12:37 UTC, r0bd0g commented
I'm going to continue to jumpslash into these for years to come.

2024-05-30 12:43 UTC, GSKirox commented
You have to jumpslash anyway to power crouch stab during the fight so it doesn't lose time overall 😄

2024-06-05 11:25 UTC, fenhl requested changes
Just a code style nit, looks good other than that.

2024-06-05 11:25 UTC, fenhl commented on Cutscenes.py
> +                   ]
```suggestion
    wonder_talk2_y_coordinates = [
        0x27C00BC, 0x27C00CC, 0x27C00DC, 0x27C00EC, 0x27C00FC, 0x27C010C, 0x27C011C, 0x27C012C, # Shadow Temple Whispering Wall Maze (Room 0)
        0x27CE080, 0x27CE090, # Shadow Temple Truthspinner (Room 2)
        0x2887070, 0x2887080, 0x2887090, # GTG Entrance Room (Room 0)
        0x2897070, # GTG Stalfos Room (Room 1)
        0x28A1144, # GTG Flame Wall Maze (Room 2)
        0x28A60F4, 0x28A6104, # GTG Pushblock Room (Room 3)
        0x28AE084, # GTG Rotating Statue Room (Room 4)
        0x28B9174, # GTG Megaton Statue Room (Room 5)
        0x28BF168, 0x28BF178, 0x28BF188, # GTG Lava Room (Room 6)
        0x28C7134, # GTG Dinolfos Room (Room 7)
        0x28D0094, # GTG Ice Arrow Room (Room 8)
        0x28D91BC, # GTG Shellblade Room (Room 9)
        0x225E7E0, # Death Mountain Crater (Room 1)
        0x32A50E4, # Thieves' Hideout Green Cell Room 3 torches (Room 1)
        0x32AD0E4, # Thieves' Hideout Red Cell Room 1 torch (Room 2)
        0x32BD102, # Thieves' Hideout Green Cell Room 4 torches (Room 4)
        0x32C1134, # Thieves' Hideout Blue Cell Room 2 torches (Room 5)
    ]
```

2024-06-06 00:48 UTC, fenhl approved these changes

2024-09-30 12:21 UTC, fenhl commented
Merged in 8de7593.

2024-09-30 12:21 UTC, fenhl commented
Got the PRs mixed up here somehow.

2024-09-30 12:29 UTC, merged