Add a setting to lock starting the game behind a password
TestRunnerSRL/OoT-Randomizer pull request #2240
Opened 2024-06-07 17:45 UTC by GSKirox

This PR adds a non-GUI setting password_lock which when enabled, make starting a file in the file select screen password protected.
This password is exposed in the spoiler log after the file hash, and is in form of A/C inputs.
The texture at the bottom of file select has been removed to show instead if the seed is still locked. Once the right password has been entered, the message will disappear and the player can start the seed normally. The normal texture is only removed when the setting is enabled.
Since we store the password information in the extended save context, the player will still need to save once in game to keep the "password clear" state.

https://github.com/OoTRandomizer/OoT-Randomizer/assets/65768236/23fd7570-1a96-4e00-84c4-f91c6ba1f7f2

2024-06-10 14:33 UTC, flagrama requested changes

2024-06-10 14:33 UTC, flagrama commented on ASM/c/file_select.c
> +#define BUTTON_HEIGHT 12
Okay, this seems like a bad habit all over the codebase, but if you need these values to only mean something in this file and some other file may have set/changed them, you should not be using `#define`. You should be using `static const type name = value`. There's no reason to continually change these values (TEXT_WIDTH and TEXT_HEIGHT are used in other files as well) and could cause bugs if someone tries to use definition expecting it to always be one thing, but then a new file is added that redefines it right before the old code uses it and now it's wrong.

A definition should only ever be set once. If you're redefining it multiple times you probably want a static (only applies to this compilation unit (c file)) const (cannot be changed, trying to do so is undefined behaviour)

2024-06-10 14:33 UTC, flagrama commented on ASM/c/save.c
> +//extern uint8_t buffer_password[PASSWORD_LENGTH];
Left in commented out code.

2024-06-10 14:33 UTC, flagrama commented on ASM/c/save.c
> +    }*/
More commented out code.

2024-06-10 14:33 UTC, flagrama commented on ASM/c/file_select.c
> +uint8_t is_saved_password_clear(z64_menudata_t* menu_data) {
You have save.h imported which means you already have stdbool.h imported. Please use `bool` type and  `true` and `false` values for these functions that amount to a true/false answer instead of `uint8_t`.

2024-06-10 14:33 UTC, flagrama commented on ASM/c/file_select.c
> +    if (menu_data->menu_transition == 3) { // In the File 1/File 2 menu.
Does decomp have an enum for this value? If so could you add it to file_select.h and use it for everywhere this variable is used? Enum values are more useful than comments.

2024-06-10 14:33 UTC, flagrama commented on ASM/c/file_select.c
> +            if (menu_data->selected_sub_item == 0) { // On the Ok option.
Similarly for this variable.

2024-06-10 14:33 UTC, flagrama commented on ASM/c/file_select.c
> +                        z64_PlaySFXID(NA_SE_SY_ERROR);
Playing the error sound when removing the first entered input seems weird. Is there not a better sound effect to use here? I understand the need to make the "state change" explicit, but the error sound should be reserved for when the menu cannot do an action (like the password being wrong so it can't unlock the file)

2024-06-10 14:33 UTC, flagrama commented on ASM/c/file_select.c
> +                        buffer_password[password_index - 1] = 0;
```suggestion
                        buffer_password[password_index] = 0;
                        password_index--;
```

2024-06-14 18:28 UTC, GSKirox commented on ASM/c/file_select.c
> +                        z64_PlaySFXID(NA_SE_SY_ERROR);
Changed it to NA_SE_SY_FSEL_CLOSE

2024-06-20 00:46 UTC, fenhl requested changes
Some code style nits, including another place `bool` can be used instead of `uint8_t`.

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +    uint8_t fileOkPassword[2] = {1, 1};
```suggestion
    bool fileOkPassword[2] = {true, true};
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +                fileOkPassword[slotFile] = 0;
```suggestion
                fileOkPassword[slotFile] = false;
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +    return (fileOkPassword[0] || fileOkPassword[1]) ? true : false;
```suggestion
    return fileOkPassword[0] || fileOkPassword[1];
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +    if (!(is_saved_password_clear(menu_data)) && !(is_buffer_password_clear())) {
```suggestion
    if (!is_saved_password_clear(menu_data) && !is_buffer_password_clear()) {
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +            draw_int_size(db, 1 + (cooldown / 60), left - 2*padding, top, color, 6, 12);
```suggestion
            colorRGBA8_t color = {0xFF, 0xFF, 0xFF, 0xFF};
            draw_int_size(db, 1 + cooldown / 60, left - 2 * padding, top, color, 6, 12);
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +        sprite_draw(db, &quest_items_sprite, 0, left + TEXT_WIDTH + 2*padding + 15*font_sprite.tile_w, top - 2, BUTTON_WIDTH, BUTTON_HEIGHT);
```suggestion
        sprite_draw(db, &quest_items_sprite, 0, left + TEXT_WIDTH + 2 * padding + 15 * font_sprite.tile_w, top - 2, BUTTON_WIDTH, BUTTON_HEIGHT);
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +                        else {
```suggestion
                        } else {
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +                    else {
```suggestion
                    } else {
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +                    else {
```suggestion
                    } else {
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.h
> +    /* 7 */ SM_LOAD_GAME
```suggestion
    /* 7 */ SM_LOAD_GAME,
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.h
> +    /* 1 */ FS_BTN_CONFIRM_QUIT
```suggestion
    /* 1 */ FS_BTN_CONFIRM_QUIT,
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/save.c
> +
```suggestion
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/save.h
> +
```suggestion
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +uint8_t buffer_password[PASSWORD_LENGTH] = {0, 0, 0, 0, 0, 0,};
```suggestion
uint8_t buffer_password[PASSWORD_LENGTH] = {0, 0, 0, 0, 0, 0};
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +            else {
```suggestion
            } else {
```

2024-06-20 00:46 UTC, fenhl commented on ASM/c/file_select.c
> +                    else {
```suggestion
                    } else {
```

2024-06-20 07:00 UTC, fenhl approved these changes

2024-06-20 21:18 UTC, fenhl commented
There's something wrong with the password input. Maybe an off-by-one when handling B inputs? Hard to tell.

https://github.com/OoTRandomizer/OoT-Randomizer/assets/641386/2bf3f321-388f-43b8-a5fe-1189c1c0e24d

2024-06-23 14:25 UTC, flagrama commented
Looks like that was my fault, sorry. I'll describe what bothers me about that code so I don't risk changing actual logic again. An index value used to access an array should match the array it is accessing. You consistently use `password_index - 1` instead of the `password_index` on its own which is a code smell that your index value is not being assigned the proper values.

2024-06-23 15:12 UTC, GSKirox commented
That's fair critisism, there was no real reason to start the index at 0 and offset everything else.

2024-06-25 03:38 UTC, fenhl commented
With that fixed, there still seems to be an issue where the password displayed in the spoiler log doesn't work. I just generated a seed which shows a password of `["C left", "C left", "C left", "C up", "C up", "C left"]` in the log but that sequence gives me the “error” sound effect.

2024-06-26 09:12 UTC, fenhl commented
Also, plandoing a password seems to be ignored — the spoiler log shows a different password.

2024-06-27 12:33 UTC, GSKirox commented
Integrated the latest fix from #2251 to solve the issue

2024-07-15 23:40 UTC, fenhl commented
There is an inconsistency with how this interacts with plandomizer: Currently, the `password` field in the plando is ignored. It should either not be ignored or be renamed to `:password` to follow the convention of other ignored fields. My view on plando features is basically that anything shown in the spoiler log should be customizable via plando if it's reasonable to implement, so I've opened https://github.com/GSKirox/OoT-Randomizer/pull/7 for the “don't ignore it” option.

2024-07-16 23:25 UTC, fenhl commented
Something seems to have gone wrong in the rebase — GSKirox#7 was merged into this PR's branch but its changes don't appear in the diff.

2024-07-17 09:14 UTC, merged