add no logic weekly preset
TestRunnerSRL/OoT-Randomizer pull request #2245
Opened 2024-06-10 21:59 UTC by shirosoluna

Add the no logic "weekly" preset that has been used for the last several months.

Notable highlights:

No logic
4 Dungeon Reward Bridge Spawn Condition
7 Dungeon Reward Ganon's Boss Key 
4 shops, random prices + shuffled merchants
Small Keysanity Anywhere
Boss Keys Regional 
Random Age
Affordable Scrubs
Dungeon Entrances + Ganon's Castle Randomized
Chest textures match content - with shields, bombchus, and upgrades in major chests
Strong Hints + Magic 
Random cuccos
Bombchu bag and drops enabled
Blue Fire Arrows enabled
Multiple Misc hints for skull house, hookshot, frogs
No disabled locations

2024-06-13 14:49 UTC, fenhl requested changes

2024-06-13 14:49 UTC, fenhl commented on .vscode/settings.json
Please remove this file.

2024-06-13 15:09 UTC, shirosoluna commented on .vscode/settings.json
deleted, hopefully done correctly

2024-06-13 15:46 UTC, fenhl commented
Before this can be fully reviewed, please take care of the failing CI checks first.

2024-06-13 16:24 UTC, shirosoluna commented
sorry, I dont have python locally to check this so just doing this in github web for now which has its pros/cons
should be resolved for the 3 issues that I saw from the CI checks

2024-06-16 14:51 UTC, fenhl approved these changes

2024-07-15 21:38 UTC, merged