Kak gate fix
TestRunnerSRL/OoT-Randomizer pull request #2250
Opened 2024-06-16 03:57 UTC by rrealmuto

Fixes a recently introduced issue where the Kak Gate setting doesn't work when set to "Open" if you don't start with zelda's letter. Also makes it so that if you find the letter while in the Kak scene with the setting set to "Zelda's Letter Opens Gate", the gate will open automatically and not require reloading the scene.

Should probably be tested with all of the different permutations of this setting + starting w/ letter + the dungeon reward shuffle which is what broke this to begin with.

https://github.com/OoTRandomizer/OoT-Randomizer/assets/5086838/ae1ed386-9d97-47a8-ad10-5ae5f8c787cc

2024-06-16 04:11 UTC, rrealmuto commented
There's still a little weird behavior where if you find the letter in kak and then talk to the guard, he still thinks you haven't handed it in. You can still hand it in and then the cutscene plays. The gate will remain open.

2024-06-16 15:08 UTC, fenhl requested changes
Just some code style nits, seems good other than that.

2024-06-16 15:08 UTC, fenhl commented on ASM/c/item_effects.c
> +                if(curr->actor_id == 0x100) { // Check for BG_GATE_SHUTTER
```suggestion
            while (curr != NULL) {
                if (curr->actor_id == 0x100) { // Check for BG_GATE_SHUTTER
```

2024-06-16 15:08 UTC, fenhl commented on ASM/src/bg_gate_shutter.asm
> +    jr  ra
```suggestion
    li      t8, OPEN_KAKARIKO
    lb      t8, 0x00(t8) ; read the value of the OPEN_KAKARIKO setting. If we set it to 2 then it's always open
    jr      ra
```

2024-06-22 04:29 UTC, fenhl approved these changes

2024-06-25 11:31 UTC, merged