Stick/Nut Upgrade Model Improvements
TestRunnerSRL/OoT-Randomizer pull request #2313
Opened 2024-09-30 23:08 UTC by rrealmuto

This PR adds a flame/smoke effect to the stick/nut upgrade GI models as shown below.

![GLideN64_THE_LEGEND_OF_ZELDA_081](https://github.com/user-attachments/assets/c048aa65-9a4a-4c5c-9456-335cee59762d)
![GLideN64_THE_LEGEND_OF_ZELDA_080](https://github.com/user-attachments/assets/548a8811-3988-4f45-8f18-7ee41546e023)
![GLideN64_THE_LEGEND_OF_ZELDA_079](https://github.com/user-attachments/assets/c0b995b2-ecb4-46a0-a0c2-f10925d668fb)
![GLideN64_THE_LEGEND_OF_ZELDA_078](https://github.com/user-attachments/assets/20c34a51-088a-40e6-88c0-2e7d53090cc6)

2024-10-01 16:10 UTC, RawZ06 commented
It would be nice to have a same effect for magic meter maybe ?

2024-10-28 08:42 UTC, GSKirox requested changes
A couple of formatting nitpicks

2024-10-28 08:42 UTC, GSKirox commented on ASM/c/item_draw_functions.h
> +void draw_gi_opa_with_flame(z64_game_t *game, uint32_t draw_id);
```suggestion
void draw_gi_flame(z64_game_t* game, colorRGBA8_t prim, colorRGBA8_t env);
void draw_gi_opa_with_flame(z64_game_t* game, uint32_t draw_id);
```

2024-10-28 08:42 UTC, GSKirox commented on ASM/c/item_draw_functions.c
> +
```suggestion
```

2025-01-06 08:15 UTC, GSKirox approved these changes

2025-04-20 18:09 UTC, rrealmuto commented
Updated the magic scroll model with rainbow smoke and removed the glow that was around the jar. What do we want to do for double magic?

2025-04-20 18:15 UTC, fenhl commented
I'd say keep the two identical for now and update it if/when we get a separate model?

2025-04-24 01:22 UTC, merged