Fix key rings being hinted as small key when keys are in their own dungeons
TestRunnerSRL/OoT-Randomizer pull request #2317
Opened 2024-10-19 11:12 UTC by GSKirox

If a keyring is placed on a hinted spot but keys are in their own dungeons, it will be hinted as a Small key, because it will be treated as an Unshuffled dungeon item, and default back to its type name, which is currently SmallKey.

To reproduce, use a hint distribution that hints Skull Mask as always, put small keys in their own dungeons and plando a keyring on Skull Mask : 
```
  "locations":                 {
    "Deku Theater Skull Mask":                              "Small Key Ring (Forest Temple)"
  }
```

The fix proposed is to give their own types to keyrings, and give it a generic type hint which will be used in this case.

2024-10-19 19:12 UTC, cjohnson57 approved these changes

2024-10-19 22:41 UTC, fenhl requested changes

2024-10-19 22:41 UTC, fenhl commented on HintList.py
> +    'TCGSmallKeyRing':                                          (["the keys to becoming a winner"], "a Game Key Ring", 'item'),
I like this cryptic hint text better than the old one (`Small Key Ring (Treasure Chest Game)`), but the old one should be changed for consistency.

2024-10-19 22:41 UTC, fenhl commented on HintList.py
> +    'HideoutSmallKeyRing':                                      (["a pack of get out of jail free cards"], "a Jail Key Ring", 'item'),
For consistency with the existing hint.

```suggestion
    'HideoutSmallKeyRing':                                      (["a deck of get out of jail free cards"], "a Jail Key Ring", 'item'),
```

2024-10-22 16:25 UTC, fenhl approved these changes

2024-10-22 19:00 UTC, merged