Implementation of 100 Skulltula Check
TestRunnerSRL/OoT-Randomizer pull request #2325
Opened 2024-11-04 04:21 UTC by Jaybone25

PR Contains the implementation of a 100 Gold Skulltula check.

In this PR I have also taken the liberty of moving the Skulltula Misc hints out of hacks.asm and into /Hacks/ovl_en_ssh.asm to clean up the hacks file, and added the code for the 100 Skulltula Misc hint in this file as well.

Current implementation has it as a default check, if desired, I can make it a setting, however it didn't feel correct to make something a setting that can just be excluded on another tab.

Since this would potentially affect current presets, I have went through and disabled the check in all presets except Hell Mode, as it felt appropriate to keep it in there.

2024-11-04 04:36 UTC, fenhl commented
I feel like this should be a setting. It's normally a repeatable item which isn't typically something included in the basic set of shuffled locations. It also follows precedent set by frog shuffle being a setting even though it works much more like a regular check.

2024-11-04 04:39 UTC, Jaybone25 commented
That's fine.  I can do this.   I just expected leaving it as default would be the preferred way since you can just disable checks form the excluded checks area so this setting kind of has the same function as that.

I'll expand the setting then to make it a list of which skull checks to turn on then, so that you can turn off any of the skull checks from there rather than just the 100.

2024-11-04 04:52 UTC, fenhl commented
I don't think expanding the setting makes sense, since that would be redundant with excluding locations, and the other skull checks already exist so the frog shuffle precedent doesn't apply.

2024-11-04 05:14 UTC, Jaybone25 commented
Sounds good

2024-11-04 05:29 UTC, cjohnson57 commented
Agree with Fenhl, since it's a non-standard location type it should be a setting

2024-11-05 06:22 UTC, fenhl requested changes

2024-11-05 06:22 UTC, fenhl commented on World.py
> +        tokens = [100, 50, 40, 30, 20, 10]
`100` should be conditionally added to this list based on the setting.

2024-11-05 06:57 UTC, Jaybone25 commented
Sounds good.  I wasn’t 100% sure what that code was doing, but I’ll make it conditional, as well as fix the error with the CI checks.  Sent from my iPhoneOn Nov 5, 2024, at 12:22 AM, Fenhl ***@***.***> wrote:﻿
@fenhl requested changes on this pull request.



In World.py:
> @@ -267,7 +267,7 @@ def __missing__(self, dungeon_name: str) -> EmptyDungeonInfo:
             max_tokens = max(max_tokens, self.settings.lacs_tokens)
         if self.settings.shuffle_ganon_bosskey == 'tokens':
             max_tokens = max(max_tokens, self.settings.ganon_bosskey_tokens)
-        tokens = [50, 40, 30, 20, 10]
+        tokens = [100, 50, 40, 30, 20, 10]

100 should be conditionally added to this list based on the setting.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-06 02:01 UTC, fenhl requested changes

2024-11-06 02:01 UTC, fenhl commented on SettingsList.py
> +            by collectioning all 100 gold skulltulas.
```suggestion
            by collecting all 100 gold skulltulas.
```

2024-11-06 11:20 UTC, fenhl approved these changes

2024-12-05 22:29 UTC, cjohnson57 requested changes

2024-12-05 22:29 UTC, cjohnson57 commented on data/Glitched World/Overworld.json
> +            "Kak 100 Gold SKulltula Reward": "(Gold_Skulltula_Token, 100)",
Typo "S**K**ulltula"

2024-12-05 22:29 UTC, cjohnson57 commented on data/World/Overworld.json
> +            "Kak 100 Gold SKulltula Reward": "(Gold_Skulltula_Token, 100)",
Typo "S**K**ulltula"

2024-12-05 22:36 UTC, fenhl commented
With 100 skulls being included in Hell Mode, Gbk should probably be changed to 20 hearts to have those required as well.

2024-12-05 22:47 UTC, r0bd0g commented
Nothing about having this check shuffled actually forces 100 gs to be collected every time though?

2024-12-05 22:54 UTC, Jaybone25 commented
Thx should be fixed as soon as the tests go through.

2024-12-06 00:23 UTC, fenhl commented
> Nothing about having this check shuffled actually forces 100 gs to be collected every time though?

Right, but now there's a check which can potentially require the tokens, which isn't the case for the hearts.

2024-12-06 02:49 UTC, r0bd0g commented
It's not super likely that something required goes on 100. I think 100 wincon is still worse just b/c there's so many more of them.

2024-12-06 04:39 UTC, cjohnson57 commented
> It's not super likely that something required goes on 100. I think 100 wincon is still worse just b/c there's so many more of them.

I agree with this after giving it some thought. 100GS bridge should still be a higher number of required checks, on average

2024-12-06 07:23 UTC, fenhl commented
Yeah, that's fair.

2024-12-06 08:21 UTC, Jaybone25 commented
Agreed.  I just made it mostly cause you can do some plando stuff with it and I’ve seen it requested before.  You could def get some keys/bks there but not a ton else.Sent from my iPhoneOn Dec 6, 2024, at 1:24 AM, Fenhl ***@***.***> wrote:﻿
Yeah, that's fair.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-12-17 07:51 UTC, cjohnson57 approved these changes

2025-06-07 00:30 UTC, fenhl commented
Small change that needs to be done here, now that #2343 has been merged: the new misc. hint needs a `text_style` field. Can be done while merging this.

How much has this been tested?

2025-06-07 01:03 UTC, Jaybone25 commented
I ran several tests when I wrote it.  Tested various combinations of misc hints on and off.  Tested various settings skulls shuffled etc.Sent from my iPhoneOn Jun 6, 2025, at 7:31 PM, Fenhl ***@***.***> wrote:﻿fenhl left a comment (OoTRandomizer/OoT-Randomizer#2325)
Small change that needs to be done here, now that #2343 has been merged: the new misc. hint needs a text_style field. Can be done while merging this.
How much has this been tested?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-06-07 01:09 UTC, fenhl commented
Okay, I'll call that sufficiently tested then, combined with it having been on my branch for 5 months now with no issues reported.

2025-06-07 01:20 UTC, merged