Creation of Skull Mask/Mask of Truth Misc Hint
TestRunnerSRL/OoT-Randomizer pull request #2343
Opened 2024-12-30 01:25 UTC by Jaybone25

Creates a Skull Mask and Mask of Truth misc hint, located on the sign in the Deku Theater.   The hint will hint either one individually if they are selected, or both if both are selected as a dual hint.

![image](https://github.com/user-attachments/assets/bb917d63-6c0c-418c-93c1-d378cd8102f9)

![image](https://github.com/user-attachments/assets/c0b49ad7-cc14-4e1e-a7ce-c8e30394b6dd)

2024-12-30 01:29 UTC, r0bd0g commented
The hints are missing final punctuation.

In the big poe misc hint PR, a location was added for the hint. I'm curious why that was necessary there but not here?

2024-12-30 01:30 UTC, Jaybone25 commented
> The hint texts are missing final punctuation.
> 
> In the big poe misc hint PR, a location was added to the logic for the hint. I'm curious why that was necessary there but not here?

Will update punctuation.   Can you show me exactly what you were talking about for the big poe?

2024-12-30 01:33 UTC, Jaybone25 commented
> > The hint texts are missing final punctuation.
> > In the big poe misc hint PR, a location was added to the logic for the hint. I'm curious why that was necessary there but not here?
> 
> Will update punctuation. Can you show me exactly what you were talking about for the big poe?

I found it.  I'll add that, i see its there for the skull hints as well.

2025-04-17 16:10 UTC, fenhl requested changes

2025-04-17 16:10 UTC, fenhl commented on HintList.py
> +    'Deku Theater Mask of Truth':   lambda world: (not world.settings.complete_mask_quest and 'Mask of Truth' not in world.settings.shuffle_child_trade) and not ('mask_of_truth' not in world.settings
Any particular reason for the double negative here? If not, I'd suggest removing it to make the code easier to read.

2025-04-17 16:10 UTC, fenhl commented on Hints.py
> +            if hint_type not in ['skull_mask', 'mask_of_truth'] and hint_type not in world.settings.misc_hints:
```suggestion
            if hint_type not in ('skull_mask', 'mask_of_truth') and hint_type not in world.settings.misc_hints:
```

2025-04-17 16:10 UTC, fenhl commented on Hints.py
> +            world.settings.misc_hints.append('mask_shop_dual')
Mutating the `settings` object should be avoided, it can cause issues since there are some parts of the codebase that assume it remains static. Maybe you could make this less hardcoded and check for corresponding single/dual misc. location hints where relevant?

2025-04-17 16:10 UTC, fenhl commented on SettingsList.py
> +            in Deku Theater will tell the reward for both items.
I feel like this can be reworded and combined into one paragraph. This tooltop is already verbose enough.

2025-04-19 01:48 UTC, fenhl commented
We'd like to see some more testing:

* Make sure it removes the hint from gossip stones if the misc. hint is on
* How it behaves if one or both masks are disabled checks
* If it breaks if spoiler log/hints are disabled since it broke the big Poes one

2025-04-19 09:00 UTC, Jaybone25 commented
I’ve already tested all of this.  I can get some screenshots though Sent from my iPhoneOn Apr 18, 2025, at 8:49 PM, Fenhl ***@***.***> wrote:﻿
  We'd like to see some more testing:

Make sure it removes the hint from gossip stones if the misc. hint is on
How it behaves if one or both masks are disabled checks
If it breaks if spoiler log/hints are disabled since it broke the big Poes one
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



fenhl left a comment (OoTRandomizer/OoT-Randomizer#2343)
We'd like to see some more testing:

Make sure it removes the hint from gossip stones if the misc. hint is on
How it behaves if one or both masks are disabled checks
If it breaks if spoiler log/hints are disabled since it broke the big Poes one


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-04-19 09:06 UTC, Jaybone25 commented
I left the hint even if it’s disabled since that’s how the skull house misc hints were.  There was discussion in dev-public about this when I was working on it, and the decision was made to follow the same way the skull house hints worked and if you select you want the misc hint for one or both of the masks, even if it’s disabled it will hint it.Not aware of how the poe misc hint broke spoiler logs, but I dug through a fair amount during testing before PRing and they looked fine to me.I’ll get the other edits you asked for when I have some time next week.Sent from my iPhoneOn Apr 19, 2025, at 4:00 AM, Jay Kilpatrick ***@***.***> wrote:﻿I’ve already tested all of this.  I can get some screenshots though Sent from my iPhoneOn Apr 18, 2025, at 8:49 PM, Fenhl ***@***.***> wrote:﻿
  We'd like to see some more testing:

Make sure it removes the hint from gossip stones if the misc. hint is on
How it behaves if one or both masks are disabled checks
If it breaks if spoiler log/hints are disabled since it broke the big Poes one
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



fenhl left a comment (OoTRandomizer/OoT-Randomizer#2343)
We'd like to see some more testing:

Make sure it removes the hint from gossip stones if the misc. hint is on
How it behaves if one or both masks are disabled checks
If it breaks if spoiler log/hints are disabled since it broke the big Poes one


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-06-03 03:50 UTC, fenhl commented
I've opened https://github.com/Jaybone25/OoT-Randomizer/pull/9 addressing the review comments.

2025-06-03 03:55 UTC, fenhl approved these changes

2025-06-03 04:17 UTC, merged